"use client";

import { useEffect, useRef, useState } from "react";
import { Conversation } from "@elevenlabs/client";
import { CallShell, reportBackgrounded, requestWakeLock, type CallStatus } from "./call-shell";

/**
 * ElevenLabs counterpart to vapi-live-call.tsx — same overall lifecycle
 * (StrictMode double-invoke guard, wake lock, backgrounded reporting,
 * elapsed timer) but two real differences from Vapi's flow:
 *
 * 1. ElevenLabs doesn't allow starting a conversation from just a public key
 *    the way Vapi does — a short-lived signed URL has to be minted
 *    server-side first (see /api/interviews/[interviewId]/elevenlabs-session
 *    and src/lib/elevenlabs/client.ts's fetchSignedUrl), so there's an async
 *    step before `Conversation.startSession()` can even be called.
 * 2. The event callback names/shapes differ: `onConnect`/`onDisconnect`
 *    mirror Vapi's `call-start`/`call-end`, and the first `onModeChange`
 *    transition to `"speaking"` mirrors Vapi's first `speech-start`.
 */
export function ElevenLabsLiveCall({
  interviewId,
  firstName,
  onEnded,
}: {
  interviewId: string;
  firstName: string;
  onEnded: () => void;
}) {
  const [status, setStatus] = useState<CallStatus>("connecting");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [elapsedSeconds, setElapsedSeconds] = useState(0);
  const conversationRef = useRef<Conversation | null>(null);
  const startedRef = useRef(false);
  const callActiveRef = useRef(false);
  const wakeLockRef = useRef<WakeLockSentinel | null>(null);
  const hasStartedSpeakingRef = useRef(false);

  useEffect(() => {
    // Same StrictMode-double-invoke guard as vapi-live-call.tsx — starting a
    // real ElevenLabs conversation isn't safely re-runnable either.
    if (startedRef.current) return;
    startedRef.current = true;

    let elapsedIntervalId: ReturnType<typeof setInterval> | undefined;

    function releaseWakeLock() {
      wakeLockRef.current?.release().catch(() => {});
      wakeLockRef.current = null;
    }

    function handleVisibilityChange() {
      if (document.visibilityState === "hidden") {
        if (callActiveRef.current) reportBackgrounded(interviewId);
      } else if (callActiveRef.current) {
        void requestWakeLock().then((lock) => {
          wakeLockRef.current = lock;
        });
      }
    }
    document.addEventListener("visibilitychange", handleVisibilityChange);

    async function start() {
      const res = await fetch(`/api/interviews/${interviewId}/elevenlabs-session`, {
        method: "POST",
      });
      if (!res.ok) {
        setStatus("error");
        setErrorMessage("The voice interviewer isn't configured yet.");
        return;
      }
      const { signedUrl } = (await res.json()) as { signedUrl: string };

      let conversation: Awaited<ReturnType<typeof Conversation.startSession>>;
      try {
        conversation = await Conversation.startSession({
          signedUrl,
          // `customLlmExtraBody` (per @elevenlabs/client's SessionConfig type)
          // is what actually reaches our custom-LLM endpoint as
          // `elevenlabs_extra_body` (see elevenlabs/custom-llm-handler.ts).
          // `dynamicVariables` is kept alongside it so the post-call
          // webhook's `conversation_initiation_client_data.dynamic_variables`
          // also carries interviewId (see elevenlabs/webhook-handler.ts) —
          // confirmed against a real payload. `firstName` here is what lets
          // the agent's dashboard-configured "First message" field reference
          // `{{firstName}}` for a personalized greeting, the same
          // templating mechanism as the `{{participant_name}}` placeholder
          // in a Vapi study's custom prompt.
          customLlmExtraBody: { interviewId },
          dynamicVariables: { interviewId, firstName },
          onConnect: () => {
            // Mirrors Vapi's "starting" phase — the transport connected, but
            // Riley's opening line (generated by our custom-LLM endpoint, see
            // voice-session/elevenlabs/custom-llm-handler.ts) hasn't been
            // spoken yet.
            setStatus("starting");
            callActiveRef.current = true;
            void requestWakeLock().then((lock) => {
              wakeLockRef.current = lock;
            });
          },
          onModeChange: ({ mode }: { mode: "speaking" | "listening" }) => {
            if (mode !== "speaking" || hasStartedSpeakingRef.current) return;
            hasStartedSpeakingRef.current = true;

            setStatus("in-progress");
            const startedAtMs = Date.now();
            setElapsedSeconds(0);
            elapsedIntervalId = setInterval(() => {
              setElapsedSeconds(Math.floor((Date.now() - startedAtMs) / 1000));
            }, 1000);
          },
          onDisconnect: (details) => {
            // TEMPORARY — logging the real disconnect reason while
            // diagnosing early/unexpected disconnects. `details` carries
            // `reason` ("error" | "agent" | "user") plus a message/context
            // that's otherwise silently discarded.
            console.log("[ElevenLabs] onDisconnect:", details);
            callActiveRef.current = false;
            releaseWakeLock();
            if (elapsedIntervalId) clearInterval(elapsedIntervalId);
            setStatus("ended");
            onEnded();
          },
          onError: (message: string) => {
            callActiveRef.current = false;
            releaseWakeLock();
            if (elapsedIntervalId) clearInterval(elapsedIntervalId);
            setStatus("error");
            setErrorMessage(message || "Call error");
          },
        });
      } catch (error) {
        // `startSession` rejects (rather than calling `onError`) for setup
        // failures like a rejected mic-permission prompt or a WebSocket
        // handshake that never completes — without this catch, that
        // rejection was unhandled and the UI sat on "Connecting…" forever
        // with nothing in the console to explain why.
        console.error("Failed to start the ElevenLabs conversation:", error);
        setStatus("error");
        setErrorMessage(error instanceof Error ? error.message : "Call error");
        return;
      }

      conversationRef.current = conversation;
    }

    start().catch((error: unknown) => {
      console.error("Failed to start the ElevenLabs call:", error);
      setStatus("error");
      setErrorMessage(error instanceof Error ? error.message : "Call error");
    });

    // Deliberately no cancellation/`conversation.endSession()` here, and no
    // `cancelled` flag gating `start()`'s continuation — same reasoning as
    // vapi-live-call.tsx's cleanup, but a harder requirement here: React 18
    // StrictMode's dev-only phantom mount->cleanup->remount cycle runs this
    // cleanup synchronously, before the `elevenlabs-session` fetch above has
    // even resolved. A `cancelled` flag set here previously caused `start()`
    // to silently bail out the instant its `await`s resumed — no error, no
    // WebSocket attempt, just a permanent "Connecting…" hang, since the
    // second (real, persisting) effect invocation is guarded out by
    // `startedRef` and never retries. Letting `start()` always run to
    // completion avoids that; the underlying call is still only ever
    // stopped via ElevenLabs' own `onDisconnect` event, same as Vapi.
    return () => {
      if (elapsedIntervalId) clearInterval(elapsedIntervalId);
      document.removeEventListener("visibilitychange", handleVisibilityChange);
      releaseWakeLock();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- start the call exactly once per mount
  }, []);

  return <CallShell status={status} errorMessage={errorMessage} elapsedSeconds={elapsedSeconds} />;
}
