"use client";

import { useEffect, useRef, useState } from "react";
import Vapi from "@vapi-ai/web";
import { CallShell, reportBackgrounded, requestWakeLock, type CallStatus } from "./call-shell";

/**
 * T11.3 — starts the Vapi web call as soon as this screen mounts (consent
 * and mic permission were already established by the intro screen; Vapi's
 * `.start()` is what actually triggers the browser's mic permission
 * prompt). `metadata: { interviewId }` is read server-side via
 * `call.assistantOverrides.metadata` (webhook) / a top-level `metadata`
 * field (custom-LLM) — see M6's PROGRESS.md for why the shape has to be
 * exactly this.
 */
export function VapiLiveCall({
  interviewId,
  onEnded,
}: {
  interviewId: string;
  onEnded: () => void;
}) {
  const [status, setStatus] = useState<CallStatus>("connecting");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [elapsedSeconds, setElapsedSeconds] = useState(0);
  const vapiRef = useRef<Vapi | null>(null);
  const startedRef = useRef(false);
  // Mirrors `status` for the visibilitychange handler, which closes over a
  // stale `status` from the effect's first run otherwise — this ref is
  // updated alongside every setStatus call below.
  const callActiveRef = useRef(false);
  const wakeLockRef = useRef<WakeLockSentinel | null>(null);
  // Guards the call-start -> in-progress transition so only Riley's first
  // utterance triggers it — `speech-start` fires again on every subsequent
  // thing Riley says for the rest of the call.
  const hasStartedSpeakingRef = useRef(false);

  useEffect(() => {
    // React 18 StrictMode double-invokes effects in development (mount →
    // cleanup → mount again) to surface unsafe side effects. Starting a real
    // Vapi call isn't safely re-runnable — without this guard, the second
    // invocation created a second, independent call for the same interview
    // (confirmed via two separate `201`s from `POST /call/web` in a captured
    // HAR), and the two calls fighting over the same microphone is what
    // produced a "Call error" for the participant. The guard survives the
    // phantom cleanup/re-invoke because refs, unlike effect-local variables,
    // aren't reset by it.
    if (startedRef.current) return;
    startedRef.current = true;

    const publicKey = process.env.NEXT_PUBLIC_VAPI_PUBLIC_KEY;
    const assistantId = process.env.NEXT_PUBLIC_VAPI_ASSISTANT_ID;
    if (!publicKey || !assistantId) {
      setStatus("error");
      setErrorMessage("The voice interviewer isn't configured yet.");
      return;
    }

    const vapi = new Vapi(publicKey);
    vapiRef.current = vapi;
    let elapsedIntervalId: ReturnType<typeof setInterval> | undefined;

    function releaseWakeLock() {
      wakeLockRef.current?.release().catch(() => {});
      wakeLockRef.current = null;
    }

    function handleVisibilityChange() {
      if (document.visibilityState === "hidden") {
        if (callActiveRef.current) reportBackgrounded(interviewId);
      } else if (callActiveRef.current) {
        // Per spec, the wake lock is auto-released on backgrounding and does
        // not auto-reacquire — must be explicitly re-requested here or it
        // silently stops protecting after the first background/foreground
        // cycle.
        void requestWakeLock().then((lock) => {
          wakeLockRef.current = lock;
        });
      }
    }
    document.addEventListener("visibilitychange", handleVisibilityChange);

    vapi.on("call-start", () => {
      // The Vapi assistant is configured with firstMessageMode:
      // "assistant-speaks-first-with-model-generated-message", so Riley's
      // opening line is generated by our custom-LLM endpoint (see
      // voice-session/vapi/custom-llm-handler.ts) from an empty conversation
      // history rather than a static `firstMessage`. Generating that
      // greeting (DB lookups + the Claude call) reliably takes several
      // seconds — "call-start" only means the transport connected, not that
      // Riley has said anything yet, so this is a distinct "starting" phase
      // rather than jumping straight to "go ahead and talk" (see the
      // `speech-start` handler below for when Riley actually begins
      // speaking).
      setStatus("starting");
      callActiveRef.current = true;
      void requestWakeLock().then((lock) => {
        wakeLockRef.current = lock;
      });
    });
    vapi.on("speech-start", () => {
      // Fires on every utterance Riley makes for the rest of the call —
      // only the first one marks the actual start of the interview.
      if (hasStartedSpeakingRef.current) return;
      hasStartedSpeakingRef.current = true;

      setStatus("in-progress");
      // T13.4 — elapsed time starts ticking once Riley actually starts
      // talking, not at raw call-start (which can precede it by several
      // seconds while the opening greeting is generated).
      const startedAtMs = Date.now();
      setElapsedSeconds(0);
      elapsedIntervalId = setInterval(() => {
        setElapsedSeconds(Math.floor((Date.now() - startedAtMs) / 1000));
      }, 1000);
    });
    vapi.on("call-end", () => {
      callActiveRef.current = false;
      releaseWakeLock();
      if (elapsedIntervalId) clearInterval(elapsedIntervalId);
      setStatus("ended");
      onEnded();
    });
    vapi.on("error", (error: unknown) => {
      callActiveRef.current = false;
      releaseWakeLock();
      if (elapsedIntervalId) clearInterval(elapsedIntervalId);
      setStatus("error");
      setErrorMessage(error instanceof Error ? error.message : "Call error");
    });

    vapi.start(assistantId, { metadata: { interviewId } });

    // Deliberately no `vapi.stop()` here. Calling it from this cleanup would
    // also fire on StrictMode's phantom cleanup — which runs immediately
    // after the effect above, before the call has even connected — ending
    // every dev-mode call before it could start. There's no manual "End
    // call" button (T11.3 — the participant ends the call by asking Riley,
    // who says END_CALL_PHRASE per vapi/custom-llm-handler.ts); the call is
    // only ever stopped via Vapi's own `call-end` event
    // (`maxDurationSeconds` / `endCallPhrases`), which already calls
    // `onEnded()` and unmounts this component — so by the time an unmount
    // happens in the normal flow, the call is already over.
    return () => {
      if (elapsedIntervalId) clearInterval(elapsedIntervalId);
      document.removeEventListener("visibilitychange", handleVisibilityChange);
      releaseWakeLock();
      vapiRef.current?.removeAllListeners();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- start the call exactly once per mount
  }, []);

  return <CallShell status={status} errorMessage={errorMessage} elapsedSeconds={elapsedSeconds} />;
}
